spring:
     
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    data:
        mongodb:
            host: localhost
            port: 27017
            database: testTechnique
           
         
server:
    contextPath: /comm
    port: 7070
logging:
    file: ./testTechnique.log
        